const GENRE_IT: Record<string, string> = {
  // Generi base cross-media
  'Action': 'Azione',
  'Action & Adventure': 'Azione & Avventura',
  'Adventure': 'Avventura',
  'Animation': 'Animazione',
  'Comedy': 'Commedia',
  'Crime': 'Crimine',
  'Documentary': 'Documentario',
  'Drama': 'Dramma',
  'Family': 'Famiglia',
  'Fantasy': 'Fantasy',
  'History': 'Storia',
  'Horror': 'Horror',
  'Music': 'Musica',
  'Mystery': 'Mistero',
  'Romance': 'Romantico',
  'Science Fiction': 'Fantascienza',
  'Sci-Fi': 'Fantascienza',
  'Sci-Fi & Fantasy': 'Fantascienza & Fantasy',
  'Thriller': 'Thriller',
  'War': 'Guerra',
  'Western': 'Western',
  'Sports': 'Sport',
  'Sport': 'Sport',
  'Psychological': 'Psicologico',
  'Supernatural': 'Soprannaturale',
  'Slice of Life': 'Slice of Life',
  'Mecha': 'Mecha',
  'Isekai': 'Isekai',
  'Kids': 'Bambini',
  'Talk': 'Talk show',
  'Reality': 'Reality',
  'Soap': 'Soap opera',
  'News': 'Notizie',

  // IGDB
  'Role-playing (RPG)': 'GDR',
  'Shooter': 'Sparatutto',
  'Strategy': 'Strategia',
  'Simulation': 'Simulazione',
  'Puzzle': 'Puzzle',
  'Racing': 'Corse',
  'Fighting': 'Picchiaduro',
  'Platform': 'Platform',
  "Hack and slash/Beat 'em up": 'Picchiaduro',
  'Real Time Strategy (RTS)': 'Strategia in tempo reale',
  'Turn-based strategy (TBS)': 'Strategia a turni',
  'Tactical': 'Tattico',
  'Visual Novel': 'Visual Novel',
  'Massively Multiplayer Online (MMO)': 'MMO',
  'Indie': 'Indie',
  'Arcade': 'Arcade',
  'Pinball': 'Pinball',
  'Quiz/Trivia': 'Quiz',
  'Card & Board Game': 'Gioco di carte',
  'Point-and-click': 'Punta e clicca',
  'Beat em up': 'Picchiaduro',

  // Board game categories (BGG)
  'Abstract Strategy': 'Strategia astratta',
  'Area Control / Area Influence': 'Controllo territorio',
  'Cooperative Play': 'Cooperativo',
  'Deck / Pool Building': 'Costruzione mazzo',
  'Deduction': 'Deduzione',
  'Dice Rolling': 'Dado',
  'Economic': 'Economico',
  'Hand Management': 'Gestione mano',
  'Legacy Game': 'Legacy',
  'Negotiation': 'Negoziazione',
  'Party Game': 'Party game',
  'Push Your Luck': 'Prendi o lascia',
  'Set Collection': 'Raccolta set',
  'Social Deduction': 'Deduzione sociale',
  'Trading': 'Commercio',
  'Trick-taking': 'Presa',
  'Wargame': 'Wargame',
  'Worker Placement': 'Piazzamento lavoratori',
  'Bluffing': 'Bluff',
  'Tile Placement': 'Posizionamento tessere',
  'Engine Building': 'Costruzione motore',
  'Route / Network Building': 'Costruzione reti',
  'Variable Player Powers': 'Poteri asimmetrici',

  // Book genres (Google Books)
  'Fiction': 'Narrativa',
  'Nonfiction': 'Saggistica',
  'Non-fiction': 'Saggistica',
  'Biography & Autobiography': 'Biografia',
  'Biography': 'Biografia',
  'Self-Help': 'Self-help',
  'Business & Economics': 'Economia',
  'Computers': 'Informatica',
  'Cooking': 'Cucina',
  'Education': 'Istruzione',
  'Games & Activities': 'Giochi',
  'Graphic Novels': 'Graphic novel',
  'Health & Fitness': 'Salute',
  'Humor': 'Umorismo',
  'Juvenile Fiction': 'Narrativa giovani',
  'Juvenile Nonfiction': 'Saggistica giovani',
  'Literary Fiction': 'Narrativa letteraria',
  'Literary Criticism': 'Critica letteraria',
  'Mathematics': 'Matematica',
  'Medical': 'Medicina',
  'Nature': 'Natura',
  'Philosophy': 'Filosofia',
  'Poetry': 'Poesia',
  'Political Science': 'Politica',
  'Psychology': 'Psicologia',
  'Religion': 'Religione',
  'Science': 'Scienza',
  'Social Science': 'Scienze sociali',
  'Technology & Engineering': 'Tecnologia',
  'Travel': 'Viaggio',
  'True Crime': 'Cronaca nera',
  'Young Adult Fiction': 'Young adult',
  'Young Adult': 'Young adult',
}

export function translateGenre(genre: string): string {
  return GENRE_IT[genre] ?? genre
}

export function translateGenres(genres: string[]): string[] {
  return genres.map(translateGenre)
}