// src/lib/reco/genre-maps.ts
// Mappe generi cross-media per il Taste Engine
// Estratto da api/recommendations/route.ts — Fix #14 Repair Bible

export const CROSS_TO_IGDB_GENRE: Record<string, string[]> = {
  'Action':           ['Action', "Hack and slash/Beat 'em up", 'Fighting', 'Shooter'],
  'Adventure':        ['Adventure', 'Role-playing (RPG)', 'Point-and-click'],
  'Fantasy':          ['Role-playing (RPG)', 'Adventure'],
  'Science Fiction':  ['Shooter', 'Strategy', 'Role-playing (RPG)'],
  'Horror':           ['Adventure'],
  'Mystery':          ['Adventure', 'Puzzle', 'Point-and-click'],
  'Drama':            ['Role-playing (RPG)', 'Visual Novel'],
  'Romance':          ['Visual Novel'],
  'Comedy':           ['Platform', 'Arcade'],
  'Thriller':         ['Action', 'Shooter'],
  'Psychological':    ['Role-playing (RPG)', 'Puzzle'],
  'Supernatural':     ['Role-playing (RPG)', 'Adventure'],
  'Slice of Life':    ['Simulation'],
  'Sports':           ['Sport', 'Racing'],
  'Sci-Fi':           ['Shooter', 'Strategy', 'Role-playing (RPG)'],
  'Mecha':            ['Action', 'Shooter'],
  'Strategy':         ['Strategy', 'Real Time Strategy (RTS)', 'Turn-based strategy (TBS)', 'Tactical'],
  'Simulation':       ['Simulation'],
  'Crime':            ['Action', 'Adventure'],
  'Survival':         ['Adventure', 'Action'],
  'Role-playing (RPG)': ['Role-playing (RPG)'],
  'Shooter':          ['Shooter'],
  'Platform':         ['Platform'],
  'Puzzle':           ['Puzzle'],
  'Indie':            ['Indie'],
  'Sandbox':          ['Simulation', 'Adventure'],
  'Fighting':         ['Fighting', "Hack and slash/Beat 'em up"],
}

export const CROSS_TO_IGDB_THEME: Record<string, number[]> = {
  'Horror':        [19],
  'Thriller':      [20],
  'Drama':         [31],
  'Science Fiction': [18],
  'Sci-Fi':        [18],
  'Fantasy':       [17],
  'Psychological': [31, 20],
}

export const IGDB_VALID_GENRES = new Set([
  'Action', 'Adventure', 'Role-playing (RPG)', 'Shooter', 'Strategy',
  'Simulation', 'Puzzle', 'Racing', 'Sport', 'Fighting', 'Platform',
  "Hack and slash/Beat 'em up", 'Real Time Strategy (RTS)', 'Turn-based strategy (TBS)',
  'Tactical', 'Visual Novel', 'Card & Board Game', 'Massively Multiplayer Online (MMO)',
  'Battle Royale', 'Indie', 'Arcade', 'Music', 'Point-and-click',
])

export const TMDB_GENRE_MAP: Record<string, number> = {
  'Action': 28, 'Adventure': 12, 'Animation': 16, 'Comedy': 35, 'Crime': 80,
  'Documentary': 99, 'Drama': 18, 'Family': 10751, 'Fantasy': 14, 'History': 36,
  'Horror': 27, 'Music': 10402, 'Mystery': 9648, 'Romance': 10749,
  'Science Fiction': 878, 'Thriller': 53, 'War': 10752, 'Western': 37,
  'Azione': 28, 'Avventura': 12, 'Animazione': 16, 'Commedia': 35, 'Crimine': 80,
  'Documentario': 99, 'Dramma': 18, 'Fantasia': 14, 'Storia': 36, 'Orrore': 27,
  'Musica': 10402, 'Mistero': 9648, 'Romantico': 10749, 'Fantascienza': 878,
  'Guerra': 10752,
}

export const TMDB_TV_GENRE_MAP: Record<string, number> = {
  ...TMDB_GENRE_MAP,
  'Action & Adventure': 10759, 'Kids': 10762, 'Reality': 10764,
  'Sci-Fi & Fantasy': 10765, 'Talk': 10767,
}

export const IGDB_TO_CROSS_GENRE: Record<string, string[]> = {
  'Role-playing (RPG)': ['Fantasy', 'Adventure', 'Drama'],
  'Action': ['Action', 'Adventure'],
  'Adventure': ['Adventure', 'Fantasy'],
  'Shooter': ['Action', 'Thriller', 'Science Fiction'],
  "Hack and slash/Beat 'em up": ['Action'],
  'Strategy': ['Strategy'],
  'Simulation': ['Simulation'],
  'Horror': ['Horror', 'Thriller', 'Mystery'],
  'Puzzle': ['Mystery', 'Drama'],
  'Platform': ['Adventure', 'Comedy'],
  'Stealth': ['Thriller', 'Action', 'Crime'],
  'Fighting': ['Action'],
  'Visual Novel': ['Drama', 'Romance', 'Mystery'],
  'Turn-based strategy (TBS)': ['Strategy'],
  'Survival': ['Horror', 'Thriller', 'Adventure'],
  'Battle Royale': ['Action', 'Thriller'],
  'Massively Multiplayer Online (MMO)': ['Fantasy', 'Adventure'],
  'Indie': ['Drama', 'Adventure'],
}

export const ADJACENCY_GRAPH: Record<string, string[]> = {
  'Action': ['Thriller', 'Adventure', 'Crime'],
  'Adventure': ['Fantasy', 'Action', 'Science Fiction'],
  'Fantasy': ['Adventure', 'Supernatural', 'Drama', 'Action'],
  'Science Fiction': ['Thriller', 'Mystery', 'Action', 'Drama'],
  'Thriller': ['Mystery', 'Crime', 'Horror', 'Drama'],
  'Horror': ['Mystery', 'Thriller', 'Supernatural'],
  'Drama': ['Romance', 'Mystery', 'Psychological'],
  'Mystery': ['Thriller', 'Crime', 'Psychological', 'Horror'],
  'Romance': ['Drama', 'Comedy', 'Slice of Life'],
  'Comedy': ['Romance', 'Slice of Life', 'Adventure'],
  'Psychological': ['Drama', 'Mystery', 'Thriller', 'Horror'],
  'Supernatural': ['Fantasy', 'Horror', 'Mystery'],
  'Sci-Fi': ['Science Fiction', 'Action', 'Mystery'],
  'Crime': ['Thriller', 'Mystery', 'Drama'],
  'Role-playing (RPG)': ['Fantasy', 'Adventure', 'Action'],
  'Strategy': ['Simulation', 'Puzzle'],
  'Simulation': ['Strategy', 'Adventure'],
  'Sports': ['Action', 'Comedy'],
  'Slice of Life': ['Comedy', 'Romance', 'Drama'],
}
// ── BGG categories → generi cross-media ──────────────────────────────────────
// Permette al taste engine di usare i gusti boardgame per consigliare altri media

export const BGG_TO_CROSS_GENRE: Record<string, string[]> = {
  'Abstract Strategy':            ['Strategy', 'Puzzle'],
  'Adventure':                    ['Adventure', 'Fantasy', 'Action'],
  'Area Control / Area Influence': ['Strategy', 'Action'],
  'Bluffing':                     ['Mystery', 'Thriller', 'Social Deduction'],
  'Card Game':                    ['Strategy', 'Puzzle'],
  'Cooperative Play':             ['Adventure', 'Fantasy', 'Drama'],
  'Deck / Pool Building':         ['Strategy', 'Adventure'],
  'Deduction':                    ['Mystery', 'Thriller', 'Crime'],
  'Dice Rolling':                 ['Action', 'Adventure'],
  'Economic':                     ['Strategy', 'Drama'],
  'Engine Building':              ['Strategy', 'Science Fiction'],
  'Fantasy':                      ['Fantasy', 'Adventure', 'Supernatural'],
  'Fighting':                     ['Action', 'Adventure'],
  'Hand Management':              ['Strategy', 'Puzzle'],
  'Horror':                       ['Horror', 'Thriller', 'Mystery'],
  'Legacy Game':                  ['Drama', 'Adventure'],
  'Medieval':                     ['Fantasy', 'History', 'Action'],
  'Miniatures':                   ['Action', 'Fantasy', 'Science Fiction'],
  'Murder/Mystery':               ['Mystery', 'Crime', 'Thriller'],
  'Mythology':                    ['Fantasy', 'Adventure', 'Supernatural'],
  'Negotiation':                  ['Drama', 'Crime'],
  'Party Game':                   ['Comedy', 'Family'],
  'Puzzle':                       ['Mystery', 'Psychological', 'Puzzle'],
  'Racing':                       ['Action', 'Sports'],
  'Role Playing':                 ['Fantasy', 'Adventure', 'Drama'],
  'Science Fiction':              ['Science Fiction', 'Thriller', 'Action'],
  'Set Collection':               ['Strategy', 'Puzzle'],
  'Social Deduction':             ['Mystery', 'Thriller', 'Crime'],
  'Space Exploration':            ['Science Fiction', 'Adventure'],
  'Strategy':                     ['Strategy', 'Tactical'],
  'Tile Placement':               ['Strategy', 'Puzzle'],
  'Trick-taking':                 ['Strategy', 'Puzzle'],
  'Variable Player Powers':       ['Strategy', 'Fantasy'],
  'Wargame':                      ['Strategy', 'History', 'Action'],
  'Worker Placement':             ['Strategy', 'Economic'],
  'Zombies':                      ['Horror', 'Action', 'Thriller'],
}

// Generi cross-media → categorie BGG per consigliare boardgame
export const CROSS_TO_BGG_CATEGORY: Record<string, string[]> = {
  'Action':           ['Adventure', 'Fighting', 'Dice Rolling'],
  'Adventure':        ['Adventure', 'Cooperative Play', 'Role Playing'],
  'Comedy':           ['Party Game', 'Bluffing'],
  'Crime':            ['Deduction', 'Social Deduction', 'Murder/Mystery'],
  'Drama':            ['Legacy Game', 'Cooperative Play'],
  'Fantasy':          ['Fantasy', 'Role Playing', 'Mythology'],
  'Horror':           ['Horror', 'Cooperative Play'],
  'Mystery':          ['Deduction', 'Social Deduction', 'Murder/Mystery'],
  'Psychological':    ['Deduction', 'Social Deduction', 'Puzzle'],
  'Romance':          ['Party Game', 'Cooperative Play'],
  'Science Fiction':  ['Science Fiction', 'Space Exploration', 'Strategy'],
  'Sci-Fi':           ['Science Fiction', 'Space Exploration'],
  'Slice of Life':    ['Party Game', 'Economic'],
  'Sports':           ['Racing', 'Sport'],
  'Strategy':         ['Strategy', 'Abstract Strategy', 'Wargame'],
  'Supernatural':     ['Horror', 'Fantasy', 'Mythology'],
  'Thriller':         ['Social Deduction', 'Deduction', 'Horror'],
  'War':              ['Wargame', 'Strategy'],
  'Western':          ['Adventure', 'Strategy'],
}

// ── Google Books categories → generi cross-media ──────────────────────────────

export const BOOK_TO_CROSS_GENRE: Record<string, string[]> = {
  'Fiction':                   ['Drama', 'Adventure'],
  'Literary Fiction':          ['Drama', 'Psychological'],
  'Mystery':                   ['Mystery', 'Crime', 'Thriller'],
  'Thriller':                  ['Thriller', 'Mystery', 'Action'],
  'Horror':                    ['Horror', 'Thriller', 'Supernatural'],
  'Romance':                   ['Romance', 'Drama'],
  'Science Fiction':           ['Science Fiction', 'Adventure'],
  'Fantasy':                   ['Fantasy', 'Adventure', 'Supernatural'],
  'Adventure':                 ['Adventure', 'Action'],
  'Historical Fiction':        ['History', 'Drama'],
  'Crime':                     ['Crime', 'Mystery', 'Thriller'],
  'Biography':                 ['Drama', 'History'],
  'Biography & Autobiography': ['Drama', 'History'],
  'Self-Help':                 ['Drama', 'Psychological'],
  'Psychology':                ['Psychological', 'Drama'],
  'Philosophy':                ['Psychological', 'Drama'],
  'True Crime':                ['Crime', 'Mystery', 'Thriller'],
  'Young Adult Fiction':       ['Drama', 'Adventure', 'Romance'],
  'Graphic Novels':            ['Action', 'Adventure', 'Drama'],
  'Humor':                     ['Comedy'],
  'Poetry':                    ['Drama'],
  'War':                       ['War', 'Drama', 'History'],
  'Mythology':                 ['Fantasy', 'Supernatural', 'History'],
}

export const CROSS_TO_BOOK_GENRE: Record<string, string[]> = {
  'Action':           ['Adventure', 'Thriller'],
  'Adventure':        ['Adventure', 'Fiction'],
  'Comedy':           ['Humor', 'Fiction'],
  'Crime':            ['Crime', 'Mystery', 'True Crime'],
  'Drama':            ['Literary Fiction', 'Fiction'],
  'Fantasy':          ['Fantasy', 'Mythology'],
  'History':          ['Historical Fiction', 'Biography & Autobiography'],
  'Horror':           ['Horror'],
  'Mystery':          ['Mystery', 'Crime', 'True Crime'],
  'Psychological':    ['Psychology', 'Philosophy', 'Thriller'],
  'Romance':          ['Romance'],
  'Science Fiction':  ['Science Fiction'],
  'Sci-Fi':           ['Science Fiction'],
  'Slice of Life':    ['Literary Fiction', 'Self-Help'],
  'Supernatural':     ['Horror', 'Fantasy'],
  'Thriller':         ['Thriller', 'Mystery', 'Crime'],
  'War':              ['War', 'Historical Fiction'],
  'Western':          ['Adventure', 'Fiction'],
}
